- README.md
> Fixes links

- .gitignore
- .travis.yml
- pypesto/objective/amici_objective.py
- pypesto/objective/objective.py
- pypesto/startpoint/util.py
- test/test_sbml_conversion.py
1) fixes an issue with startpoint resampling
2) removes redundant computation of lower order derivatives for AmiciObjective
3) adds some debug logging to amici objective
> Various small bugfixes

- pypesto/optimize/optimizer.py
> Fix re 'DeprecationWarning: Flags not at the start of the expression'

- README.md
- doc/index.rst
Some more badges (tests passing, code coverage, code quality, docs passing) :)
> Feature badges

- pypesto/profile/profiler.py
- pypesto/visualize/parameters.py
- pypesto/visualize/profiles.py
- pypesto/visualize/waterfall.py
- test/test_visualize.py
Implements customizable figure sizes with defaults optimized for jupyter notebooks.
> Figure sizes

- pypesto/optimize/optimizer.py
* logger.info fval after each local run
* log a little more
* fix minor error, format output
> logger.info fval after each local run (#163)

- README.md
- doc/index.rst
> add zenodo badge in README and index

- .travis_pip_reqs.txt
- pypesto/objective/amici_objective.py
- pypesto/objective/petab_import.py
- setup.py
In the long run, pyPESTO's petab-importer should be replaced more and more by the one from Amici...
This is the first (very barebones) step for it. Now pyPESTO should be able to import PEtab models with constant species. I don't add a unit test for this, as this functionality is tested within AMICI.
> Feature constant species

- .travis.yml
* Run notebooks only on pull requests.
> run notebooks only on pull requests

- pypesto/objective/petab_import.py
- setup.py
responding to https://github.com/PEtab-dev/PEtab/pull/344
> Fix parameter mapping

- pypesto/objective/amici_objective.py
- pypesto/objective/history.py
- pypesto/objective/objective.py
- test/test_amici_objective.py
> Remove circular dependence history-objective

- pypesto/objective/petab_import.py
- test/test_engine.py
> implement amici solver to/from hdf5 for pickling for PEtabObjective

- doc/api_engine.rst
- doc/api_objective.rst
- doc/api_optimize.rst
- doc/api_problem.rst
- doc/api_profile.rst
- doc/api_result.rst
- doc/api_sample.rst
- doc/api_startpoint.rst
- doc/api_visualize.rst
- test/test_aggregated.py
- test/test_amici_objective.py
- test/test_engine.py
- test/test_logging.py
- test/test_objective.py
- test/test_optimize.py
- test/test_sbml_conversion.py
- test/test_startpoint.py
- test/test_storage.py
- test/test_x_fixed.py
- test/visualize/test_visualize.py
* Move most tests to pytest to clarify dependencies
* Use fixtures to get more informative error messages
* Adjust docs to sphinx 3.0
> Simplify tests

- test/visualize/test_visualize.py
potentially causes memory problems
> avoid opening multiple figures in tests

- pypesto/objective/__init__.py
- pypesto/objective/amici_calculator.py
- pypesto/objective/amici_objective.py
- pypesto/objective/objective.py
- pypesto/optimize/optimizer.py
- test/test_sbml_conversion.py
* tidy up objective initialization
* cache sbml test model
* disentangle amici simulation function
> Objective.initialize(); minor edits

- pypesto/modelselection/example_model_selection_definitions.tsv
- pypesto/modelselection/unique_models.py
Just merging for now, this will be cleaned up when these functions are moved into appropriate classes/files with other work.
> Unpack model selection parameter definitions.

- pypesto/objective/amici_objective.py
- test/test_sampling.py
> write amici solver settings to stream

- pypesto/objective/history.py
- pypesto/optimize/optimizer.py
- test/test_history.py
* allow requesting arbitrary indices of traces
* therefore, simplify getter functions
> implement partial trace

- pypesto/visualize/sampling.py
`Error in: ValueError: The palette list has the wrong number of colors.`
depending on the status of the vector 'converged' (if all solutions converged (->1 color), or a subset converged (->2 colors)), the color vector (-> palette) needed to be adjusted
closes #372
> Fix visu 372

- test/test_amici_objective.py
The `test.test_amici_objective.py::test_preeq_guesses` fails too often.
Either we set a random seed (what negative consequences could this have?) or we relax the tolerances even further.
> fix amici test

- pypesto/visualize/sampling.py
- Short/Small pull request:
MCMC visualization routines failed when fixed parameters where defined in the problem, since these are not sampled. Therefore the dim of the `parameter_names` did not agree with the actual sampled parameters. This is fixed now.
> small fix visu mcmc

- .travis.yml
- test/check_git_size.sh
- test/test_amici_objective.py
> outlaw large files; fixes #388

- pypesto/visualize/misc.py
- pypesto/visualize/waterfall.py
> Fix offset_y and scale_y in waterfal plot

- pypesto/petab/importer.py
bugfix + compliance to current PEtab version in prior import
> Fix PEtab import (Priors)

- pypesto/visualize/waterfall.py
Should finally fix up the last remainders of #382, which were overlooked in #441.
> Fix waterfall limits

- pypesto/petab/importer.py
closes #445 
Co-authored-by: @stobiblum
> add x_guesses argument to PetabImporter.create_problem

- pypesto/optimize/optimizer.py
- pypesto/visualize/clust_color.py
- pypesto/visualize/misc.py
- pypesto/visualize/parameters.py
- pypesto/visualize/waterfall.py
Fixed typhinting, added some additional safeguards to clust color and snuck in a small bugfixe for the fides optimizer
> fix ylims in waterfall plot if reference points are specified

- .github/workflows/deploy.yml
May fix pypi deployment via GHA
> Deploy to pypi on publishing release

- pypesto/objective/amici.py
Introduced in 995d2a9b4c40e6891df99f022fd1ef8723400cd7
> Fixup indentation error / unreachable code

- pypesto/store/save_to_hdf5.py
Noticed a small bug in my implementation.
> fixed small bug

- pypesto/objective/amici.py
Messed up in https://github.com/ICB-DCM/pyPESTO/pull/562
> Fix incorrect handling of AmiciObjective.guess_steadystate

- README.md
- doc/authors.rst
- doc/index.rst
close #497 
- @yannikschaelte should I merge to `main` instead?
> update zenodo badge

- pypesto/optimize/optimizer.py
> fix get_default_options to correctly identify if solver is least squares

- pypesto/objective/amici_calculator.py
~Requires https://github.com/AMICI-dev/AMICI/pull/1489~
> allow ls optimization depending on settings in amici model

- pypesto/objective/aesara.py
also add RDATA to return dict, if available
> do not call unprocessed objective from within aesara

- setup.cfg
- test/base/test_history.py
- test/optimize/test_optimize.py
- test/util.py
Fixes #660 to some degree (not replacement yet, but could do ...)
> Add biological test case based on CR model

- pypesto/problem.py
- pypesto/visualize/sampling.py
- test/base/test_aggregated.py
- test/base/test_engine.py
- test/base/test_history.py
- test/base/test_logging.py
- test/base/test_objective.py
- test/base/test_problem.py
- test/base/test_startpoint.py
- test/base/test_store.py
- test/base/test_x_fixed.py
> Fix axes variable overwriting; Make sure problem.x_names are unique

- pypesto/ensemble/ensemble.py
noticed an error in the entries_per_start function. Fixed it.
> ensembles -fix entries_per_start function

- setup.cfg
Makes life easier if one wants to use all pypesto features...
> Packaging: Add extras_require 'all', 'all_optimizers'

- pypesto/objective/base.py
> Raise exception if eps is supplied to check_grad_multi_eps

- pypesto/petab/importer.py
Rename column 'measurement' of simulation data frame to 'simulation (regarding issue #719)
> Update importer.py regarding issue #719

- pypesto/objective/amici.py
- pypesto/objective/amici_calculator.py
- pypesto/objective/amici_util.py
- pypesto/objective/base.py
- pypesto/objective/function.py
- test/base/test_aggregated.py
- test/util.py
> make AmiciObjective only report whats being asked for

- pypesto/logging.py
- pypesto/objective/amici_util.py
> Add log level checks; fixes #767

- doc/example.rst
- pypesto/logging.py
- pypesto/objective/amici_util.py
> Reorganize notebooks; Check log level preemptively

- pypesto/objective/finite_difference.py
- test/base/test_objective.py
* Make mode "constant" really only evaluate once
* Add mode "always"
> Fix finite difference constant mode

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- doc/install.rst
- setup.cfg
> Require python >= 3.8

- .pre-commit-config.yaml
- doc/example/amici_import.ipynb
- pypesto/ensemble/ensemble.py
- pypesto/objective/finite_difference.py
- pypesto/objective/priors.py
- pypesto/sample/auto_correlation.py
- test/base/test_objective.py
- test/base/test_prior.py
merging to petab select thingy as 2 things broken
> Update to stable black version

- pypesto/optimize/optimizer.py
- pypesto/optimize/task.py
- pypesto/result/optimize.py
- pypesto/store/save_to_hdf5.py
- pypesto/util.py
- pypesto/visualize/__init__.py
- pypesto/visualize/clust_color.py
- pypesto/visualize/optimization_stats.py
- pypesto/visualize/parameters.py
- pypesto/visualize/waterfall.py
- test/base/test_history.py
- test/visualize/test_visualize.py
Currently the summary would look like this: 
```
* number of starts: 1 
* best value found 1.0 time(s) 
* number of plateaus found: 0 
* best value: 4.7062606861955025, worst value: 4.7062606861955025 
A summary of the best run:
* optimizer used: None 
* message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH 
* number of evaluations: 24 
* time taken to optimize: 0.10471081733703613 
* endpoint: [0.05102318 0.05243334] 
* final objective value: 4.7062606861955025 
* final gradient value: [ 1.85431034e-04 -4.79956677e-05] 
```
Any feedback or wanted additions?
> Summary method

- pypesto/objective/amici.py
https://github.com/AMICI-dev/AMICI/pull/1744
> Remove useless preeq method

- doc/storage_format.md
> Updated optimization storage format. Made Attributes explicit.

- pypesto/optimize/load.py
Of course, pypesto problem can be added to the result afterwards. If you think it's unnecessary, pull-request can be deleted :)
> Read problem with results from file

- pypesto/result/optimize.py
> Revert "Added id to best value, worst value, added booleans, whether to display best/worst run summary."

- pypesto/result/optimize.py
- pypesto/result/result.py
* Round cpu time to milliseconds (everything below is generally not helpful)
* number of starts as int
* typehints
* Add `Result.summary()`
> Nicer `OptimizeResult.summary`

- README.md
- doc/api.rst
- doc/conf.py
- doc/index.rst
- pypesto/objective/base.py
- pypesto/objective/function.py
- pypesto/problem/__init__.py
- pypesto/problem/base.py
- pypesto/startpoint/base.py
- setup.cfg
* recommonmark -> myst as deprecated
* sphinx version can be unfixed again without error
* explicit language definition "en" required
> Fix doc build with latest sphinx etc

- pypesto/store/save_to_hdf5.py
* Fix missing blanks
* Make more informative (filename)
* Use less broad exception
> Fix message in `check_overwrite`

- pypesto/C.py
- pypesto/ensemble/ensemble.py
- pypesto/ensemble/util.py
- pypesto/objective/aesara.py
- pypesto/objective/aggregated.py
- pypesto/objective/amici.py
- pypesto/objective/amici_calculator.py
- pypesto/objective/amici_util.py
- pypesto/objective/base.py
- pypesto/objective/finite_difference.py
- pypesto/objective/function.py
- pypesto/objective/history.py
- pypesto/objective/priors.py
- pypesto/predict/amici_predictor.py
- pypesto/predict/task.py
> Literal typehints for `mode`

- pypesto/result/optimize.py
* Handle empty results more gracefully
* Format message summary as markdown table
* List of timings as proper markdown
> `OptimizerResult.summary()` formatting / error handling

- pypesto/petab/importer.py
> Use fake RData in prediction_to_petab_measurement_df

- pypesto/ensemble/util.py
- pypesto/optimize/util.py
- pypesto/store/__init__.py
- pypesto/store/save_to_hdf5.py
h5py already has that functionality
> Remove superfluous get_or_create_group

- test/optimize/test_optimize.py
See e.g. https://github.com/ICB-DCM/pyPESTO/runs/8266214721?check_suite_focus=true
> Fix flaky test_mpipoolengine

- pypesto/optimize/load.py
To make it reusable in other contexts
> Extract read_history_from_file from read_result_from_file

- pypesto/result/optimize.py
- setup.cfg
* Fix length check to work with both list and numpy array, as assign_clusters may return either
* Add `tabulate` as dependency (required by `pandas.DataFrame.to_markdown` used in summary)
> Fix OptimizeResult.summary

- .gitignore
- doc/example/sampler_study.ipynb
- pypesto/sample/pymc.py
- test/sample/test_sample.py
> Unsupport pymc sampler until fixed

- pypesto/visualize/waterfall.py
Fixes broken f-string from #910
> Fix waterfall plot label

- pypesto/result/optimize.py
Got broken, presumably in https://github.com/ICB-DCM/pyPESTO/pull/802
> Fix OptimizeResult pickling

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
> GHA: Update actions

- setup.cfg
Seems to be fixed
https://github.com/matplotlib/matplotlib/issues/24127
https://github.com/matplotlib/matplotlib/releases/tag/v3.6.2
> Unfix matplotlib version

- doc/api.rst
- doc/conf.py
- pypesto/visualize/model_fit.py
and fix petab-intersphinx
Closes #984
> Add pypesto.visualize.model_fit to API doc

- setup.cfg
See https://github.com/numpy/numpy/issues/22826
Fixes #990
> Exclude numpy==1.24.0

- .flake8
> Fixes #1003

- pypesto/optimize/ess/__init__.py
- pypesto/optimize/ess/cess.py
- pypesto/optimize/ess/ess.py
- pypesto/optimize/ess/function_evaluator.py
- pypesto/optimize/ess/sacess.py
- test/optimize/test_optimize.py
* Fix TypeError for size-1-arrays
* Optional arguments
* logging
* optional multiprocessing instead of multithreading
* cleanup
> Sacess fixes

- .flake8
- pypesto/hierarchical/problem.py
- pypesto/history/base.py
- pypesto/objective/base.py
- pypesto/objective/finite_difference.py
- pypesto/objective/priors.py
- pypesto/petab/importer.py
- pypesto/profile/profile_next_guess.py
- pypesto/profile/validation_intervals.py
- pypesto/result/predict.py
- pypesto/result/profile.py
- pypesto/testing/examples.py
- test/petab/test_petab_import.py
- test/petab/test_sbml_conversion.py
- test/profile/test_validation_intervals.py
> black update

- .readthedocs.yml
To run example notebooks (-> https://readthedocs.org/projects/pypesto/builds/19417900/)
> Doc: Install amici on RTD

- pypesto/engine/multi_process.py
- test/base/test_engine.py
> Allow custom multiprocessing context

- pypesto/result/optimize.py
Small typo, thanks to @dweindl
> small typo in summary

- pypesto/objective/base.py
- pypesto/petab/importer.py
There appeared some new C419 errors. removed them 👍🏼
> removed "new" flake8 error

- .github/workflows/ci.yml
> Temporarily set the version of petab installed to 1.4.2

- pypesto/result/optimize.py
- pypesto/result/result.py
Added option to show/not show the hessian in the summary, as this in general takes up the most space.
> Additional summary option

- doc/example/model_selection.ipynb
- pypesto/visualize/select.py
> Doc: Fix some typos in model selection example

- pypesto/profile/profile.py
> Fix problem overwrite of profiling

- .github/CODEOWNERS
Here is a first proposal. Feel free to add yourself to it. 
`?` are where i think a second person would be good.
> Codeowner Changes

- pypesto/optimize/ess/ess.py
In ESSOptimizer, retry local searches if we encounter a non-finite value at the startpoint. Don't add points with non-finite objective values to list of local solutions.
> ESSOptimizer: Retry local search in case of non-finite value at startpoint

- pypesto/profile/profile_next_guess.py
- pypesto/profile/walk_along_profile.py
So far, if optimization at any point of a parameter profile fails to produce a finite result, profile computation aborts (see #1148).
Therefore, as a first measure, if optimization fails, retry from another randomly sampled point.
Fixes #1148
>  Parameter profile: retry optimization in case of failure

- pypesto/ensemble/ensemble.py
- pypesto/predict/amici_predictor.py
- pypesto/visualize/ensemble.py
Adding type annotations, fixing some typos.
> Doc: Update/add/fix type annotations in ensemble+predict

- .github/workflows/ci.yml
Only until problem is solved with Sebastian.
> PEtab.jl makes problems since 2.5.1

- .github/workflows/clear-cache.yml
Might resolve frequent cache misses for Julia tests.
> GHA: Clear PR cache after merge

- .github/workflows/install_deps.sh
Fixes `.github/workflows/install_deps.sh: 13: [: Linux: unexpected operator`
https://github.com/ICB-DCM/pyPESTO/actions/runs/7265048086/job/19793906617
> GHA: Fix install_deps.sh

- .github/workflows/ci.yml
- .readthedocs.yml
- doc/conf.py
- setup.cfg
Prerequisite for #1246:
* Ubuntu 22.04 on RTD
* Install all relevant deps on RTD
* GHA: More time for documentation job
> Doc: Update sphinx/rtd config to enable re-executing notebooks

- pypesto/optimize/optimize.py
- pypesto/petab/importer.py
- setup.cfg
- test/base/test_history.py
- test/base/test_prior.py
- test/petab/test_amici_objective.py
- test/petab/test_petab_import.py
- test/petab/test_petab_suite.py
removed some deprecation warnings, amici produced
> Removed amici DeprecationWarnings

- pypesto/hierarchical/semiquantitative/solver.py
Repeating the change made in #1313. Somehow it got overwritten to the old version.
> Semiquantitative: Repeat change of #1313

- pypesto/objective/amici/amici.py
- pypesto/objective/amici/amici_calculator.py
- pypesto/visualize/model_fit.py
Seems to have missed some last time.
> Fixed some leftover amici depractions.

- .github/workflows/deploy.yml
> Changed to use API token for deployment

- .github/workflows/deploy.yml
> Removing Benchmark collection for deploy. Update action versions. (#1371)

- doc/example/roadrunner.ipynb
Removed a spacebar preventing header to be seen as such
> Correct header for roadrunner example

- setup.cfg
- tox.ini
Remove <2.0 in hopes of all problems being resolved. *fingers crossed*
> Handle numpy 2.0 with older packages

- pypesto/visualize/misc.py
> More informative info message for start indices.

- INSTALL.rst
This wasn't updated in a while ...
> Update Python requirement in INSTALL.rst

- .github/CODEOWNERS
- .github/workflows/ci.yml
- doc/authors.rst
Mainly:
- Jonas becomes sampling code owner
- Vincent takes over marens position as maintainer and takes on julia parts
Additional:
- Added Domagoj as codeowner of profiles due to recent revamp
> Changes to codeowners discussed at retreat

- tox.ini
Branch was merged to master and deleted.
> GHA: Fix pysb installation failures

- pypesto/petab/importer.py
> Added a deprecated version of create_model

- .github/workflows/install_deps.sh
Add missing symlinks.
Closes #1550.
> Fix blas/lapack linker errors on GHA runners

- pypesto/optimize/ess/sacess.py
* debug logs include time for saving intermediary results
* split file creation and tmp file deletion
* add number of local searches to worker results
> SacessOptimizer: Minor updates

- pypesto/objective/roadrunner/roadrunner_calculator.py
Extended the presimulation time and set the steady state solver to newton. Closes #1597
> Roadrunner Steady State
